[build]
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "node node-server.mjs"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production.variables]
NODE_ENV = "production"
